# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: MMM HIS NLP Dev Engine API
  description: Rapid Content Dev Engine for SME
  version: "1.0.0"
# the domain of the service
host: zchen-server.usac.mmm.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /testRequest:
    post:
      summary: Test Request
      description: |
        Send a Test Request to Dev Engine
      responses:
        202:
          description: Test Request Accepted
          schema:
            $ref: '#/definitions/Acknowledge'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
definitions:
  Acknowledge:
    type: object
    properties:
      id:
        type: integer
        format: int32
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      
